---
date: "2022-11-06"
output: markdown
---

## Load

```{r load, include=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(glue)
options(max.print = 1000)
util_folder <- c("util")
beep <- function(){
  system(str_c("notify-send 'Task complete.'",
               "&& paplay /usr/share/sounds/Yaru/stereo/message.oga"))
}
```

## Input

```{r input}
metadata <- yaml::read_yaml(here("input", "metadata.yaml"))
known_entities <- yaml::read_yaml(here("input", "known_entities.yaml")) %>%
  map_dfr(flatten_dfc) %>%
  {set_names(.$token, .$regex)}
```

## Loader

```{r load}
source(here(util_folder, "load_data.R"))
source(here("input", "load_fixes.R"))
test_data <- metadata$index[c(1,11)] %>%
    map(read_data) %>%
    map(~ fixes[[.x$group]](.x))
test_data %>%
  walk(glimpse)
```

## Entities

```{r entities}
source(here(util_folder, "get_compound_candidates.R"))

test_entities <- test_data %>%
  map(~ .x$document$content) %>%
  flatten_chr() %>%
  get_compound_candidates(known_entities)
test_entities
collocations <- test_entities$collocation
```

## Tokenize

```{r tokenize}
source(here(util_folder, "tokenize.R"))
test_tokens <- test_data %>%
  map(~ list_modify(.x, tokens = 
                      tokenize(.x$document, known_entities, collocations)))
glimpse(test_tokens)
```

## Frequency

1. Infrequent

```{r infrequent}
source(here(util_folder, "count_by_doc.R"))
source(here(util_folder, "get_frequency.R"))
frequency <- test_tokens %>%
  map_dfr(count_by_doc) %>%
  get_frequency()
frequency %>%
  arrange(frequency)
```

```{r rm_infrequent}
infrequent <- frequency %>%
  filter(frequency == 1)
frequent_tokens <- test_tokens %>%
  map(~ modify_at(.x, "tokens", ~ anti_join(.x, infrequent, by = "token")))
glimpse(frequent_tokens)
```

2. tfidf 

```{r tfidf}
source(here(util_folder, "prop_tfidf.R"))
tfidf <- frequent_tokens %>%
  map_dfr(count_by_doc) %>%
  prop_tfidf(0.08)
tfidf
```

```{r filter_tfidf}
source(here(util_folder, "remove_tfidf.R"))
cutoff = 0.002004
low_tfidf <- tfidf %>%
  filter(tf_idf < cutoff)
high_tfidf_tokens <- frequent_tokens  %>%
  map(remove_tfidf, low_tfidf)
glimpse(high_tfidf_tokens)
```

Too frequent

```{r frequent_tokens}
frequency_2 <- high_tfidf_tokens %>%
  map_dfr(count_by_doc) %>%
  get_frequency()
frequency_2 %>%
  arrange(desc(frequency))
```

```{r rm_frequent}
frequent <- frequency_2 %>%
  head()
trimmed_tokens <- test_tokens %>%
  map(~ modify_at(.x, "tokens", ~ anti_join(.x, frequent, by = "token")))
glimpse(trimmed_tokens)
```
